### ISSUE TITLE
Value of lambda

### ISSUE THREAD

**Issue by rrydbirk** [randel/HiDecon#2]
Thank you for this interesting tool!
I have a real-life example where mCCC is really low even with lambda = 2k. 

How high would you imagine/recommend lambda could be?

BR

Rasmus

**Comment by Penghuihuang2000** [comment]
Hi Rasmus,

Thank you for your interest in **HiDecon**! We suggest users to provide count per million data into **HiDecon**. If so, in my experience, a lambda smaller than 200 should work. Mostly, it's around 100.  You can also use **select_HiDecon** function to select the lamda using our resampling based parameter selection method. You can customize "_lambda.set_" specifying parameter set used for parameter selection in **select_HiDecon**. 

The low mCCC might be caused by data quality since CCC is pretty sensitive. Mean shift, disconcordant trend and large variance all can cause an extremely low mCCC. Therefore, I would also suggest to check the scatter plot.

Please feel free to ask if you have any further question.

Best,
Penghui

**Comment by rrydbirk** [comment]
Hi Penghui

Thank for your reply!

In the paper, you state:
_... the expression of each tissue sample and cell in the raw count matrix is divided by its total count and multiplied by 1,000,000 as the count per million (CPM). Then, data is log2 transformed with a pseudo count of 1 to ensure all elements are nonnegative._

From what I can see, the log2 transformation is done within HiDecon, right? But the CPM normalization isn't. From the text I understood you did both within HiDecon, so I'm a bit confused. I would urge you to reconsider the formulation of this paragraph.

I'll try providing CPM instead of raw counts.

BR 

Rasmus

**Comment by rrydbirk** [comment]
I can confirm that providing CPM values improved lambda selection. However, it's still high, around 600. I'll settle with this.

**Comment by Penghuihuang2000** [comment]
Hi Rasmus,

The paper stated the whole data preprocessing procedure to feed into the optimization. However, the software requires CPM data while the only thing package does is log2 transforming. I am sorry for this inconsistency. Thank you for your suggestion.

Best,
Penghui
