### ISSUE TITLE
`normalized` in HiDecon

### ISSUE THREAD

**Issue by KaWingLee9** [randel/HiDecon#4]
Since `normalized` needs to be specified in `select_HiDecon`, it needn't been specified in `HiDecon`. 
Any restriction of data input when using `HiDecon`?

**Comment by Penghuihuang2000** [comment]
Hi Kawing,
Thanks for your interest in HiDecon. First of all, compared with _HiDecon_ function, I will always suggest using _select_HiDecon_ since it can possibly provide a better penalty parameter. Second, in _HiDecon_ function, both "bulk" and "ref" input should be normalized data (the same normalization method). What was used in original HiDecon paper is CPM (count per million). There's no further restriction. Feel free to ask if there's any question.
Penghui

**Comment by KaWingLee9** [comment]
Oh, I see. Thank you for your reply. You really do me a favor.
